CREATE TABLE AidStations (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    timeUpdate TIME,
    StationType VARCHAR(30) NOT NULL,
    Location VARCHAR(30) NOT NULL,
    Comments VARCHAR(30) NOT NULL,
    CurrentPatients INT,
    CumulativePatients INT,
    Beds INT,
    Latitude DOUBLE,
    Longitude DOUBLE,
    Km FLOAT,
    Status INT,
    Display INT
);

CREATE TABLE RunnerData (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    time TIME,
    start INT,
    at5k INT,
    at10k INT,
    at15k INT,
    at20k INT,
    at25k INT,
    at30k INT,
    at35k INT,
    at40k INT,
    finish INT,
    OnCourse INT
);
    
    
    
CREATE TABLE RunnersPerSegment (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    temperature INT,
    minute INT,
    started INT,
    mile0 INT,
    mile1 INT,
    mile2 INT,
    mile3 INT,
    mile4 INT,
    mile5 INT,
    mile6 INT,
    mile7 INT,
    mile8 INT,
    mile9 INT,
    mile10 INT,
    mile11 INT,
    mile12 INT,
    mile13 INT,
    mile14 INT,
    mile15 INT,
    mile16 INT,
    mile16 INT,
    mile17 INT,
    mile18 INT,
    mile19 INT,
    mile20 INT,
    mile21 INT,
    mile22 INT,
    mile23 INT,
    mile24 INT,
    mile25 INT,
    mile26 INT,
    finished INT,
    km0 INT,
    km5 INT,
    km10 INT,
    km15 INT,
    km20 INT,
    km25 INT,
    km30 INT,
    km35 INT,
    km40 INT,
);
    
CREATE TABLE RunnerPerMile (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    temperature INT,
    minute INT,
    mile INT,
    runners INT
);
    
CREATE TABLE AidStationsEvent (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    timeUpdate TIME,
    AS1_comment VARCHAR(30),
    AS1_current INT,
    AS1_cumulative INT,
    AS1_status VARCHAR(30),
    AS2_comment VARCHAR(30),
    AS2_current INT,
    AS2_cumulative INT,
    AS2_status VARCHAR(30),
    AS3_comment VARCHAR(30),
    AS3_current INT,
    AS3_cumulative INT,
    AS3_status VARCHAR(30),
    AS4_comment VARCHAR(30),
    AS4_current INT,
    AS4_cumulative INT,
    AS4_status VARCHAR(30),
    AS5_comment VARCHAR(30),
    AS5_current INT,
    AS5_cumulative INT,
    AS5_status VARCHAR(30),
    AS6_comment VARCHAR(30),
    AS6_current INT,
    AS6_cumulative INT,
    AS6_status VARCHAR(30),
    AS7_comment VARCHAR(30),
    AS7_current INT,
    AS7_cumulative INT,
    AS7_status VARCHAR(30),
    AS8_comment VARCHAR(30),
    AS8_current INT,
    AS8_cumulative INT,
    AS8_status VARCHAR(30),
    AS9_comment VARCHAR(30),
    AS9_current INT,
    AS9_cumulative INT,
    AS9_status VARCHAR(30),
    AS10_comment VARCHAR(30),
    AS10_current INT,
    AS10_cumulative INT,
    AS10_status VARCHAR(30),
    AS11_comment VARCHAR(30),
    AS11_current INT,
    AS11_cumulative INT,
    AS11_status VARCHAR(30),
    AS12_comment VARCHAR(30),
    AS12_current INT,
    AS12_cumulative INT,
    AS12_status VARCHAR(30),
    AS13_comment VARCHAR(30),
    AS13_current INT,
    AS13_cumulative INT,
    AS13_status VARCHAR(30),
    AS14_comment VARCHAR(30),
    AS14_current INT,
    AS14_cumulative INT,
    AS14_status VARCHAR(30),
    AS15_comment VARCHAR(30),
    AS15_current INT,
    AS15_cumulative INT,
    AS15_status VARCHAR(30),
    AS16_comment VARCHAR(30),
    AS16_current INT,
    AS16_cumulative INT,
    AS16_status VARCHAR(30),
    AS17_comment VARCHAR(30),
    AS17_current INT,
    AS17_cumulative INT,
    AS17_status VARCHAR(30),
    AS18_comment VARCHAR(30),
    AS18_current INT,
    AS18_cumulative INT,
    AS18_status VARCHAR(30),
    AS19_comment VARCHAR(30),
    AS19_current INT,
    AS19_cumulative INT,
    AS19_status VARCHAR(30),
    AS20_comment VARCHAR(30),
    AS20_current INT,
    AS20_cumulative INT,
    AS20_beds INT,
    AS20_status VARCHAR(30),
    Balbo_comment VARCHAR(30),
    Balbo_current INT,
    Balbo_cumulative INT,
    Balbo_status VARCHAR(30),
    Indiana_comment VARCHAR(30),
    Indiana_current INT,
    Indiana_cumulative INT,
    Indiana_status VARCHAR(30),
    Ambulance_comment VARCHAR(30),
    Ambulance_current INT,
    Ambulance_cumulative INT,
    Ambulance_status VARCHAR(30),
    Podiatry_comment VARCHAR(30),
    Podiatry_current INT,
    Podiatry_cumulative INT,
    Podiatry_status VARCHAR(30),
    Jackson_comment VARCHAR(30),
    Jackson_current INT,
    Jackson_cumulative INT,
    Jackson_status VARCHAR(30),
    Laflin_comment VARCHAR(30),
    Laflin_current INT,
    Laflin_cumulative INT,
    Laflin_status VARCHAR(30),
);

CREATE TABLE IF NOT EXISTS `MarathonRunners` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `runnerId` int(11) DEFAULT NULL,
  `minute` int(11) DEFAULT NULL,
  `started` int(11) DEFAULT NULL,
  `finished` int(11) DEFAULT NULL,
  `corral` int(11) DEFAULT NULL,
  `startTime` float DEFAULT NULL,
  `position` float DEFAULT NULL,
  `deviation` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `myIndex` (`runnerId`,`minute`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;